FROM python:3.10-slim

# Ngăn python tạo file bytecode dư thừa
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Cài đặt Java 17 (Bắt buộc cho Spark) và công cụ
RUN apt-get update && \
    apt-get install -y default-jre procps wget && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập biến Java
ENV JAVA_HOME="/usr/lib/jvm/default-java"

# Cài đặt PySpark và các công cụ Python của Ingestion
RUN pip install --no-cache-dir \
    pyspark==4.1.1 \
    minio==7.2.5 \
    websocket-client==1.7.0 \
    confluent-kafka==2.3.0 \
    findspark \
    flask>=2.3.0 \
    flask-cors>=4.0.0 \
    pandas>=2.0.0

WORKDIR /app
