version: '3.8'

services:
  # ==========================================
  # LỚP 1: INGESTION (THU THẬP DỮ LIỆU)
  # ==========================================
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: lakehouse-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: lakehouse-kafka
    ports:
      - "9092:9092"   # Port cho Spark ở trong Docker gọi tới
      - "29092:29092" # Port cho Python ở ngoài máy tính của bạn gọi tới
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Cấu hình 2 luồng mạng cực kỳ quan trọng để không bị lỗi kết nối
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  # ==========================================
  # LỚP 2: STORAGE (LƯU TRỮ GỐC)
  # ==========================================
  minio:
    image: minio/minio:latest
    container_name: lakehouse-minio
    ports:
      - "9000:9000" # Port API (để Spark kết nối lưu Delta Lake)
      - "9001:9001" # Port Giao diện Web (để bạn xem file)
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data  # LƯU Ý QUAN TRỌNG: Lưu vĩnh viễn dữ liệu xuống ổ cứng máy bạn

  # ==========================================
  # LỚP 4: API & COMPUTE (XỬ LÝ - SPARK)
  # ==========================================
  spark-master:
    image: bitnami/spark:latest
    container_name: lakehouse-spark-master
    ports:
      - "8080:8080" # Port giao diện Web quản lý cụm Spark
      - "7077:7077" # Port để các Worker kết nối
    environment:
      - SPARK_MODE=master
    volumes:
      - ./workspace:/workspace # Nơi chứa code Python và file CSV 15GB của nhóm

  spark-worker:
    image: bitnami/spark:latest
    container_name: lakehouse-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./workspace:/workspace
    depends_on:
      - spark-master